### ISSUE TITLE
Method to extract frequencies

### ISSUE THREAD

**Issue by gayatrivenugopal** [Common-Voice/wikipedia-data#1]
Hi,
    I am trying to do something similar for Hindi. How did you extract the frequencies from the wiki dump?

Thanks

**Comment by nukeador** [comment]
Hi,

Please check the readme file on this repo:

https://github.com/Common-Voice/common-voice-wiki-scraper

Feel free to open any issue on that repo if you find any issues.

Thanks for your contributions!
